In [1]:
import tensorflow_datasets as tfds

In [2]:
imdb, info = tfds.load('imdb_reviews', with_info=True, as_supervised=True)

Dataset imdb_reviews downloaded and prepared to /Users/macintosh/tensorflow_datasets/imdb_reviews/plain_text/1.0.0. Subsequent calls will reuse this data.


In [6]:
import numpy as np

train_data,test_data = imdb['train'], imdb['test']

In [7]:
train_sentences=[]
test_sentences=[]

train_labels=[]
test_labels=[]

for s,l in train_data:
    train_sentences.append(str(s.numpy()))
    train_labels.append(l.numpy())
    
for s,l in test_data:
    test_sentences.append(str(s.numpy()))
    test_labels.append(l.numpy())

#0: negative
#1: positive

In [10]:
print(train_sentences[0])
print(train_labels[0])

b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it."
0


In [28]:
# nen mang thanh mang array

train_labels = np.array(train_labels)
test_labels = np.array(test_labels)

In [29]:
vocab_size=10000
embedding_dim=64
max_length=140

In [30]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [31]:
tokenizer = Tokenizer(num_words=vocab_size,oov_token='<OOV>')
tokenizer.fit_on_texts(train_sentences)

In [32]:
tokenizer.word_index

{'<OOV>': 1,
 'the': 2,
 'and': 3,
 'a': 4,
 'of': 5,
 'to': 6,
 'is': 7,
 'br': 8,
 'in': 9,
 'it': 10,
 'i': 11,
 'this': 12,
 'that': 13,
 'was': 14,
 'as': 15,
 'for': 16,
 'with': 17,
 'movie': 18,
 'but': 19,
 'film': 20,
 "'s": 21,
 'on': 22,
 'you': 23,
 'not': 24,
 'are': 25,
 'his': 26,
 'he': 27,
 'have': 28,
 'be': 29,
 'one': 30,
 'all': 31,
 'at': 32,
 'by': 33,
 'they': 34,
 'an': 35,
 'who': 36,
 'so': 37,
 'from': 38,
 'like': 39,
 'her': 40,
 "'t": 41,
 'or': 42,
 'just': 43,
 'there': 44,
 'about': 45,
 'out': 46,
 "'": 47,
 'has': 48,
 'if': 49,
 'some': 50,
 'what': 51,
 'good': 52,
 'more': 53,
 'very': 54,
 'when': 55,
 'she': 56,
 'up': 57,
 'can': 58,
 'b': 59,
 'time': 60,
 'no': 61,
 'even': 62,
 'my': 63,
 'would': 64,
 'which': 65,
 'story': 66,
 'only': 67,
 'really': 68,
 'see': 69,
 'their': 70,
 'had': 71,
 'were': 72,
 'me': 73,
 'well': 74,
 'we': 75,
 'than': 76,
 'much': 77,
 'been': 78,
 'get': 79,
 'bad': 80,
 'will': 81,
 'people': 82,
 'do': 83,

In [33]:
# Gan nguoc lai train_sequence thanh cac so theo nhu da token ben tren

train_sequences = tokenizer.texts_to_sequences(train_sentences)

In [34]:
# Cau nao dai thi cat o dang sau, cau nao ngan thi pad o dnag truoc

padded_train_sequences = pad_sequences(train_sequences,maxlen=max_length,truncating='post',padding='pre')

In [35]:
padded_train_sequences

array([[   0,    0,    0, ...,  874,  145,   10],
       [   0,    0,    0, ...,   32,   31,   47],
       [   0,    0,    0, ...,    9, 6176,   47],
       ...,
       [7629,   37,   11, ..., 2743,   21, 1563],
       [2677,   11,  216, ..., 1048,   37,   31],
       [3875,    5,   31, ...,    1, 2238,   42]], dtype=int32)

In [36]:
padded_train_sequences.shape

(25000, 140)

In [37]:
test_sequences = tokenizer.texts_to_sequences(test_sentences)

In [38]:
test_sequences[0]

[59,
 44,
 25,
 109,
 13,
 97,
 4115,
 16,
 742,
 4370,
 10,
 14,
 316,
 5,
 2,
 593,
 354,
 16,
 1864,
 1212,
 1,
 16,
 680,
 7499,
 5595,
 1,
 773,
 6,
 13,
 1037,
 1,
 1,
 439,
 491,
 1,
 4,
 1,
 334,
 3610,
 20,
 229,
 3,
 15,
 5796,
 3,
 15,
 1646,
 15,
 102,
 5,
 2,
 3597,
 101,
 11,
 1450,
 1528,
 12,
 251,
 235,
 11,
 216,
 2,
 377,
 6429,
 3,
 62,
 95,
 11,
 174,
 105,
 11,
 1528,
 180,
 12,
 251,
 37,
 6,
 1144,
 1,
 682,
 7,
 4452,
 1,
 4,
 1,
 334,
 7,
 37,
 8367,
 377,
 5,
 1420,
 1,
 13,
 30,
 64,
 28,
 6,
 874,
 181,
 17,
 4,
 1050,
 5,
 12,
 224,
 3,
 83,
 4,
 353,
 33,
 353,
 5229,
 5,
 10,
 6,
 1340,
 1160,
 2,
 5738,
 1,
 3,
 1,
 5,
 10,
 175,
 328,
 7,
 1319,
 3989,
 4,
 798,
 1946,
 5,
 4,
 250,
 2710,
 158,
 3,
 2,
 361,
 31,
 187,
 25,
 1170,
 499,
 610,
 5,
 2,
 122,
 2,
 356,
 1398,
 7725,
 30,
 1,
 881,
 38,
 4,
 20,
 39,
 12,
 1,
 4,
 1,
 334,
 7,
 4,
 20,
 634,
 60,
 48,
 214]

In [39]:
padded_test_sequences = pad_sequences(test_sequences,maxlen=max_length,truncating='post',padding='post')

In [40]:
padded_test_sequences.shape

(25000, 140)

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense

In [44]:
model = Sequential()
model.add(Embedding(vocab_size, embedding_dim, input_length=max_length))
model.add(Flatten())
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['acc'])

In [45]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 140, 64)           640000    
_________________________________________________________________
flatten (Flatten)            (None, 8960)              0         
_________________________________________________________________
dense (Dense)                (None, 10)                89610     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 729,621
Trainable params: 729,621
Non-trainable params: 0
_________________________________________________________________


In [47]:
model.fit(padded_train_sequences, train_labels, epochs=30, validation_data=(padded_test_sequences,test_labels))

Epoch 1/30
782/782 [==============================] - 3s 4ms/step - loss: 2.4567e-05 - acc: 1.0000 - val_loss: 0.8280 - val_acc: 0.8250
Epoch 2/30
782/782 [==============================] - 3s 4ms/step - loss: 1.5540e-05 - acc: 1.0000 - val_loss: 0.8574 - val_acc: 0.8243
Epoch 3/30
782/782 [==============================] - 3s 4ms/step - loss: 9.9027e-06 - acc: 1.0000 - val_loss: 0.8860 - val_acc: 0.8244
Epoch 4/30
782/782 [==============================] - 3s 4ms/step - loss: 6.3485e-06 - acc: 1.0000 - val_loss: 0.9144 - val_acc: 0.8240
Epoch 5/30
782/782 [==============================] - 3s 4ms/step - loss: 4.0759e-06 - acc: 1.0000 - val_loss: 0.9371 - val_acc: 0.8255
Epoch 6/30
782/782 [==============================] - 3s 4ms/step - loss: 2.6227e-06 - acc: 1.0000 - val_loss: 0.9689 - val_acc: 0.8240
Epoch 7/30
782/782 [==============================] - 3s 4ms/step - loss: 1.6973e-06 - acc: 1.0000 - val_loss: 0.9923 - val_acc: 0.8252
Epoch 8/30
782/782 [============================

In [48]:
model.save('ReviewIMDB.h5')

In [53]:
#model.load('ReviewIMDB.h5')

AttributeError: 'Sequential' object has no attribute 'load'

In [57]:
test_sen = ['I hate this movie']
test_seq = tokenizer.texts_to_sequences(test_sen)
padded_test_seq = pad_sequences(test_seq,maxlen=max_length,truncating='post',padding='post')

In [58]:
padded_test_seq

array([[ 11, 797,  12,  18,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0]], dtype=int32)

In [59]:
model.predict(padded_test_seq)

array([[0.12208271]], dtype=float32)

In [60]:
e = model.layers[0]

In [62]:
weights = e.get_weights()[0]

In [63]:
weights

array([[ 0.0023194 , -0.0212964 , -0.03139849, ..., -0.01841907,
         0.00720988, -0.02205149],
       [ 0.00886829, -0.02700755,  0.00227501, ...,  0.02378326,
        -0.01052224, -0.02281274],
       [-0.00168047, -0.01024627,  0.01053926, ...,  0.04673434,
         0.00430513, -0.02123425],
       ...,
       [-0.10401668, -0.01142212,  0.07445484, ..., -0.10396796,
         0.02838613,  0.1223598 ],
       [-0.12701538, -0.06373634, -0.0737795 , ..., -0.002627  ,
        -0.02612734, -0.01639268],
       [ 0.07709398,  0.00911457,  0.00095368, ...,  0.05434759,
        -0.05478144, -0.02130033]], dtype=float32)

In [68]:
import io

out_v = io.open('vecs.tsv','w',encoding='utf-8')
out_m = io.open('meta.tsv','w',encoding='utf-8')

for i in range (1,vocab_size):
    word=tokenizer.index_word[i]
    vector=weights[i]
    out_m.write(word + '\n')
    out_v.write('\t'.join(str(x) for x in vector) + '\n')
    
out_m.close()
out_v.close()

In [65]:
print(tokenizer.index_word)

{1: '<OOV>', 2: 'the', 3: 'and', 4: 'a', 5: 'of', 6: 'to', 7: 'is', 8: 'br', 9: 'in', 10: 'it', 11: 'i', 12: 'this', 13: 'that', 14: 'was', 15: 'as', 16: 'for', 17: 'with', 18: 'movie', 19: 'but', 20: 'film', 21: "'s", 22: 'on', 23: 'you', 24: 'not', 25: 'are', 26: 'his', 27: 'he', 28: 'have', 29: 'be', 30: 'one', 31: 'all', 32: 'at', 33: 'by', 34: 'they', 35: 'an', 36: 'who', 37: 'so', 38: 'from', 39: 'like', 40: 'her', 41: "'t", 42: 'or', 43: 'just', 44: 'there', 45: 'about', 46: 'out', 47: "'", 48: 'has', 49: 'if', 50: 'some', 51: 'what', 52: 'good', 53: 'more', 54: 'very', 55: 'when', 56: 'she', 57: 'up', 58: 'can', 59: 'b', 60: 'time', 61: 'no', 62: 'even', 63: 'my', 64: 'would', 65: 'which', 66: 'story', 67: 'only', 68: 'really', 69: 'see', 70: 'their', 71: 'had', 72: 'were', 73: 'me', 74: 'well', 75: 'we', 76: 'than', 77: 'much', 78: 'been', 79: 'get', 80: 'bad', 81: 'will', 82: 'people', 83: 'do', 84: 'also', 85: 'other', 86: 'into', 87: 'because', 88: 'great', 89: 'first', 90: